# Generated by Django 3.1.7 on 2021-03-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0003_auto_20210324_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='current_song',
        ),
    ]
