# Generated by Django 3.2.2 on 2021-05-17 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='code',
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.CharField(default='user1', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='content',
            field=models.CharField(default='No_String', max_length=200),
        ),
    ]
