# Generated by Django 3.2.2 on 2021-05-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210517_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.CharField(default='No_String', max_length=50),
        ),
    ]
